### ISSUE TITLE
Can not reproduce the paper results?

### ISSUE THREAD

**Issue by zhiweihu1103** [zjukg/MorsE#1]
I used the default script in your github repository to reproduce the code on the four sub-datasets of FB15k-237 use TransE mode, and found that the results of the paper could not be reproduced even after running many times. The following is the comparison between the paper and my reproduced results. Can you give your exact operating parameter information and look forward to your reply.
![微信截图_20220810213426](https://user-images.githubusercontent.com/17820697/183914763-76424ad3-cdbb-444c-bb27-078b7131767d.png)

**Comment by AnselCmy** [comment]
Thanks for your interest in our work. We use the same hyper-parameters as the code in our Github repo. Did you try using different subgraphs? The released code only conducts generating subgraphs before experiments once, while you can modify the hard-coded ‘args.db_path’ for meta-training the model using different subgraphs since the process of generating subgraphs contains some randomness and may influence the final results a little bit.
